namespace: monitoring

resources:
  - namespace.yml
  - node-exporter/deployment.yml
  - prometheus/statefulset.yml
  - grafana/pvc.yml
  - grafana/deployment.yml

configMapGenerator:
  - name: monitoring-prometheus-config
    files:
      - prometheus/prometheus.yml
  - name: monitoring-grafana-provisioning-dashboards-config
    files:
      - grafana/provisioning/dashboards/dashboards.yml
  - name: monitoring-grafana-provisioning-datasources-config
    files:
      - grafana/provisioning/datasources/datasources.yml
  - name: monitoring-grafana-dashboards-config
    files:
      - grafana/dashboards/munchies.json
      - grafana/dashboards/musiccollection.json
      - grafana/dashboards/notes.json
      - grafana/dashboards/system.json

secretGenerator:
  - name: monitoring-grafana-secret
    envs:
      - secrets/grafana.env
