services:
  monitoring-node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    networks:
      - monitoring

  monitoring-prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    command:
      - "--storage.tsdb.retention.time=15d"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - monitoring-node-exporter
    networks:
      - monitoring

  monitoring-grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    ports:
      - 3000:3000
    env_file: grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    name: monitoring
