apiVersion: 1

datasources:
  - name: notes
    uid: fkdi59flh03jd7
    type: mysql
    url: notes-mysql:3306
    user: ${NOTES_USERNAME}
    access: proxy
    jsonData:
      database: ${NOTES_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${NOTES_PASSWORD}
  - name: prometheus
    uid: ef98vg6y97da8a
    type: prometheus
    url: http://monitoring-prometheus:9090
    access: proxy
    jsonData:
      httpMethod: GET
