apiVersion: 1

datasources:
  - name: munchies
    uid: df95d61129vy8b
    type: mysql
    url: munchies-mysql:3306
    user: ${MUNCHIES_USERNAME}
    access: proxy
    jsonData:
      database: ${MUNCHIES_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${MUNCHIES_PASSWORD}
  - name: musiccollection
    uid: mu3kf8s5asm98n
    type: postgres
    url: ${MUSICCOLLECTION_URL}
    user: ${MUSICCOLLECTION_USERNAME}
    access: proxy
    jsonData:
      database: ${MUSICCOLLECTION_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${MUSICCOLLECTION_PASSWORD}
  - name: musiccollection-keycloak
    uid: mukey3jg9hknu4
    type: postgres
    url: ${MUSICCOLLECTION_KEYCLOAK_URL}
    user: ${MUSICCOLLECTION_KEYCLOAK_USERNAME}
    access: proxy
    jsonData:
      database: ${MUSICCOLLECTION_KEYCLOAK_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${MUSICCOLLECTION_KEYCLOAK_PASSWORD}
  - name: prometheus
    uid: ef98vg6y97da8a
    type: prometheus
    url: http://monitoring-prometheus:9090
    access: proxy
    jsonData:
      httpMethod: GET
