apiVersion: v1
kind: Service
metadata:
  name: monitoring-node-exporter
spec:
  type: ClusterIP
  selector:
    app: monitoring-node-exporter
  ports:
    - port: 9100
      targetPort: 9100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-node-exporter
spec:
  selector:
    matchLabels:
      app: monitoring-node-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-node-exporter
    spec:
      containers:
        - name: monitoring-node-exporter
          image: prom/node-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
